image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Initialize Project"
    init: |
      chmod +x setup.sh
    command: |
      bash setup.sh && python run.py

ports:
  - port: 5000
    onOpen: open-preview
