image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Initialize Project"
    init: |
      sudo ip link add eth1 type dummy
      sudo ip link set eth1 up
      chmod +x setup.sh
    command: |
      bash setup.sh && python run.py

ports:
  - port: 5000
    onOpen: open-preview
